[Engine]

# 将棋ソフトの表示名です。
Name = "Kifuwarakaku Bld3"

# 将棋ソフトの制作者名です。
Author = "Satoshi TAKAHASHI"

[Resources]

Michi187 = "../../Data/data_michi187.csv"
Haiyaku185 = "../../Data/data_haiyaku185_UTF-8.csv"
InputForcePromotion = "../../Data/data_forcePromotion_UTF-8.csv"
OutputForcePromotion = "../../Logs/_log_強制転成表.html"
InputSyuruiToHaiyaku = "../../Data/data_syuruiToHaiyaku.csv"
OutputSyuruiToHaiyaku = "../../Logs/_log_配役転換表.html"
OutputSyuruiToHaiyaku01DataRowOnly = "../../Logs/_log_配役転換表Load(1)_データ行のみ.txt"
OutputSyuruiToHaiyaku02Load = "../../Logs/_log_配役転換表Load(2).txt"

Fv00Komawari = "../../Data/fv/fv_00_Komawari.csv"
Fv00KomawariSample = "../../Data/fv_00_Komawari(sample).csv"
Fv00Scale = "../../Data/fv/fv_00_Scale.csv"
Fv01KK = "../../Data/fv_01_KK.csv"
Fv2Sample = "../../Data/fv_2(sample).csv"

Fv00ScaleInFvDir = "fv_00_Scale.csv"
Fv01KKInFvDir = "fv_01_KK.csv"
Fv02n1pKPInFvDir = "fv_02_1pKP.csv"
Fv03n2pKPInFvDir = "fv_03_2pKP.csv"
Fv04PP1pInFvDir = "fv_04_PP_1p____Fu__.csv"
Fv05PP1pInFvDir = "fv_05_PP_1p____Kyo_.csv"

Fv06pp1pInFvDir = "fv_06_pp_1p____Kei_.csv"
Fv07pp1pInFvDir = "fv_07_pp_1p____Gin_.csv"
Fv08pp1pInFvDir = "fv_08_pp_1p____Kin_.csv"
Fv09pp1pInFvDir = "fv_09_pp_1p____Hi__.csv"
Fv10pp1pInFvDir = "fv_10_pp_1p____Kaku.csv"

Fv18pp2pInFvDir = "fv_18_pp_2p____Fu__.csv"
Fv19pp2pInFvDir = "fv_19_pp_2p____Kyo_.csv"
Fv20pp2pInFvDir = "fv_20_pp_2p____Kei_.csv"
Fv21pp2pInFvDir = "fv_21_pp_2p____Gin_.csv"
Fv22pp2pInFvDir = "fv_22_pp_2p____Kin_.csv"
Fv23pp2pInFvDir = "fv_23_pp_2p____Hi__.csv"
Fv24pp2pInFvDir = "fv_24_pp_2p____Kaku.csv"

Fv11PP1pInFvDir = "fv_11_PP_1pMotiFu__.csv"
Fv25pp2pInFvDir = "fv_25_pp_2pMotiFu__.csv"

Fv12PP1pInFvDir = "fv_12_PP_1pMotiKyo_.csv"
Fv13PP1pInFvDir = "fv_13_pp_1pMotiKei_.csv"
Fv14PP1pInFvDir = "fv_14_pp_1pMotiGin_.csv"
Fv15PP1pInFvDir = "fv_15_pp_1pMotiKin_.csv"
Fv26PP2pInFvDir = "fv_26_pp_2pMotiKyo_.csv"
Fv27PP2pInFvDir = "fv_27_pp_2pMotiKei_.csv"
Fv28PP2pInFvDir = "fv_28_pp_2pMotiGin_.csv"
Fv29PP2pInFvDir = "fv_29_pp_2pMotiKin_.csv"

Fv16pp1pInFvDir = "fv_16_pp_1pMotiHi__.csv"
Fv17pp1pInFvDir = "fv_17_pp_1pMotiKaku.csv"
Fv30pp2pInFvDir = "fv_30_pp_2pMotiHi__.csv"
Fv31pp2pInFvDir = "fv_31_pp_2pMotiKaku.csv"

Shogiban01Widgets = "../../Data/data_widgets_01_shogiban.csv"
Console02Widgets = "../../Data/data_widgets_02_console.csv"
Vs03Widgets = "../../Data/data_widgets_03_vs.csv"

DataSetteiCsv = "../../Data/data_settei.csv"
DataSetteiVsCsv = "../../Data/data_settei_vs.csv"

DataSetteiXml = "../../Data/data_settei.xml"
AimsDataSetteiXml = "./CSharp/Builds/Engine/Data/data_settei.xml"

# ログ・ファイル(拡張子は付けないでください)

N01ErrorLog = "../../Logs/_log_エラー"
N02DefaultSennititeLog = "../../Logs/_log_Default_千日手判定"
N03ServerDefaultLog = "../../Logs/_log_ｻｰﾊﾞｰ_ﾃﾞﾌｫﾙﾄ"
N04ServerNetworkAsyncLog = "../../Logs/_log_ｻｰﾊﾞｰ_非同期通信"
N05CsharpGuiDefaultLog = "../../Logs/_log_CsharpGUI_ﾃﾞﾌｫﾙﾄ"
N06CsharpGuiKifuYomitoriLog = "../../Logs/_log_CsharpGUI_棋譜読取"
N07CsharpGuiNetworkLog = "../../Logs/_log_CsharpGUI_通信"
N08CsharpGuiPaintLog = "../../Logs/_log_CsharpGUI_ﾍﾟｲﾝﾄ"
N09CsharpGuiSennititeLog = "../../Logs/_log_CsharpGui_千日手判定"
N10AimsDefaultLog = "../../Logs/_log_AIMS対応用_ﾃﾞﾌｫﾙﾄ"
N11EngineDefaultLog = "../../Logs/_log_ｴﾝｼﾞﾝ_ﾃﾞﾌｫﾙﾄ"
N12EngineNetworkLog = "../../Logs/_log_ｴﾝｼﾞﾝ_通信"
N13EngineMousouRirekiLog = "../../Logs/_log_ｴﾝｼﾞﾝ_妄想履歴"
N14EngineSennititeLog = "../../Logs/_log_ｴﾝｼﾞﾝ_千日手判定"
N15TestProgramLog = "../../Logs/_log_テスト・プログラム用（汎用）"
N16LearnerLog = "../../Logs/_log_棋譜学習ソフト用"
N17SpeedKeisokuLog = "../../Logs/_log_スピード計測ソフト用"

N18KifuCsaLogBasename = "CSA棋譜デバッグ.txt"
N19TedokuKeisanLog = "../../Logs/_log_手得計算.txt"
N20DebugForcePromotionLog = "../../Logs/#強制転成デバッグ.txt"

# .txt ファイル

LogDaseMeirei = "../../Logs/_log_ログ出せ命令.txt"
HyokaMeisaiLogTxtBasename = "_log_評価明細.txt"
DataStyleText = "../../Data/data_style.txt"
StopLearningFlag = "Stop_learning.txt"
SearchKifuFolderText = "Search_kifu_folder.txt"
SyugoronDirectoryText = "dictionary.txt"

# 画像

LearningPositionLogPng = "../../Logs/_log_学習局面.png"
LearningPositionLogPngBasename = "_log_学習局面.png"
Koma1PngBasename = "koma1.png"
Suji1PngBasename = "suji1.png"
ChokkinNoSasiteLogPngBasename = "_log_直近の指し手.png"

N1PngBasename = "1.png" # 出力ファイル
N2PngBasename = "2.png" # 駒画像へのパス。
N3PngBasename = "3.png" # 数字・小
